version: "3"

vars:
    apps:
        sh: ls -1 ./apps

tasks:
    format:
        desc: Run bun format in every app folder
        deps:
            - for: { var: apps }
              task: format:app
              vars:
                  APP: "{{.ITEM}}"

    format:app:
        internal: true
        cmds:
            - cd ./apps/{{.APP}} && bun format

    lint:
        desc: Run bun lint in every app folder
        deps:
            - for: { var: apps }
              task: lint:app
              vars:
                  APP: "{{.ITEM}}"

    lint:app:
        internal: true
        cmds:
            - cd ./apps/{{.APP}} && bun lint

    default:
        desc: Run bun run dev server in every app folder in parallel
        deps:
            - for: { var: apps }
              task: dev
              vars:
                  APP: "{{.ITEM}}"

    dev:
        internal: true
        cmds:
            - cd ./apps/{{.APP}} && bun run dev
