/**
 * Comprehensive word lists for prose quality analysis
 * These lists are curated specifically for fiction writing
 * Each list is designed to be conservative - only flagging clearly problematic patterns
 */

/**
 * Filter words that often weaken prose
 * These are words that add little meaning and can usually be removed
 */
export const FILTER_WORDS = [
	// Intensifiers (often unnecessary)
	'just',
	'really',
	'very',
	'quite',
	'rather',
	'somewhat',
	'actually',
	'basically',
	'literally',
	'simply',
	'totally',
	'completely',
	'absolutely',
	'definitely',
	'certainly',
	'extremely',
	'incredibly',
	'especially',
	'particularly',

	// Hedging words
	'probably',
	'possibly',
	'maybe',
	'perhaps',
	'almost',
	'nearly',
	'hardly',
	'barely',
	'slightly',

	// Vague quantifiers
	'kind of',
	'sort of',
	'a bit',
	'a little',
	'a lot',

	// Filler phrases
	'in order to',
	'start to',
	'begin to',
	'seem to',
	'appear to',
	'tend to',
	'manage to',
	'happen to',
	'decide to',

	// Distance words (often indicate filtering through POV unnecessarily)
	'suddenly',
	'immediately',
	'finally',
	'eventually',

	// Thought/perception filters (often redundant in deep POV)
	'realized',
	'noticed',
	'wondered',
	'thought',
	'knew',
	'felt',
	'heard',
	'saw',
	'watched',
	'looked',
	'seemed'
] as const;

/**
 * Vague words that could be more specific
 * These are generic terms that often indicate the writer could be more precise
 */
export const VAGUE_WORDS = [
	// Generic nouns
	'thing',
	'things',
	'stuff',
	'something',
	'anything',
	'everything',
	'nothing',
	'someone',
	'anyone',
	'everyone',
	'no one',
	'somewhere',
	'anywhere',
	'everywhere',
	'nowhere',
	'somehow',
	'anyway',
	'whatever',
	'whenever',
	'wherever',

	// Empty adjectives
	'nice',
	'good',
	'bad',
	'big',
	'small',
	'great',
	'interesting',
	'beautiful',
	'ugly',
	'amazing',
	'awesome',
	'terrible',
	'horrible',
	'wonderful',
	'fantastic',
	'incredible',
	'weird',
	'strange',
	'different',
	'normal',
	'special',
	'important',

	// Vague descriptors
	'a lot',
	'many',
	'some',
	'several',
	'various',
	'certain'
] as const;

/**
 * Common clichés in fiction writing
 * These are overused phrases that often signal lazy writing
 */
export const CLICHES = [
	// Opening clichés
	'it was a dark and stormy night',
	'once upon a time',
	'little did she know',
	'little did he know',
	'little did they know',

	// Time-related clichés
	'in the nick of time',
	'all of a sudden',
	'at the end of the day',
	'when all was said and done',
	'time will tell',
	'only time will tell',
	'time stood still',
	'in the blink of an eye',
	'before she knew it',
	'before he knew it',

	// Generic phrases
	'the fact of the matter',
	'for all intents and purposes',
	'each and every',
	'first and foremost',
	'few and far between',
	'last but not least',
	'easier said than done',
	'better late than never',
	'actions speak louder than words',
	'a needle in a haystack',
	'avoid like the plague',
	'beat around the bush',
	'bite the bullet',
	'break the ice',
	'burning the midnight oil',
	'crystal clear',
	'dead as a doornail',
	'fit as a fiddle',
	'heart of gold',
	'let the cat out of the bag',
	'once in a blue moon',
	'read between the lines',
	'sick and tired',
	'think outside the box',
	'tip of the iceberg',
	'under the weather',

	// Appearance clichés
	'white as a ghost',
	'white as a sheet',
	'white as snow',
	'black as night',
	'red as a rose',
	'green with envy',
	'blue as the sky',
	'pale as death',
	'cold as ice',
	'hard as a rock',
	'soft as silk',
	'light as a feather',
	'quiet as a mouse',
	'quick as lightning',
	'slow as molasses',
	'sharp as a tack',
	'dumb as a rock',
	'blind as a bat',
	'crazy like a fox',
	'hungry as a wolf',
	'strong as an ox',

	// Body language clichés
	'her heart skipped a beat',
	'his heart skipped a beat',
	'her heart pounded',
	'his heart pounded',
	'her heart raced',
	'his heart raced',
	'butterflies in her stomach',
	'butterflies in his stomach',
	'a chill ran down her spine',
	'a chill ran down his spine',
	'goosebumps rose on her skin',
	'goosebumps rose on his skin',
	'shivers ran down her spine',
	'shivers ran down his spine',
	"he let out a breath he didn't know he was holding",
	"she let out a breath she didn't know she was holding",
	"a breath they didn't know they were holding",
	'the world fell away',
	'his blood ran cold',
	'her blood ran cold',
	'her eyes widened',
	'his eyes widened',
	'tears streamed down her face',
	'tears streamed down his face',
	'clenched her fists',
	'clenched his fists',
	'gritted her teeth',
	'gritted his teeth',
	'balled her hands into fists',
	'balled his hands into fists',
	'rolled her eyes',
	'rolled his eyes',
	'raised an eyebrow',
	'raised her eyebrow',
	'raised his eyebrow',
	'arched an eyebrow',

	// Emotion clichés
	'scared to death',
	'worried sick',
	'bored to tears',
	'green with jealousy',
	'red with anger',
	'white with fear',
	'blind with rage',
	'consumed by guilt',
	'overcome with emotion',
	'filled with dread',

	// Eye clichés
	'piercing blue eyes',
	'steely gray eyes',
	'smoldering eyes',
	'eyes like pools',
	'eyes that sparkled',
	'fire in her eyes',
	'fire in his eyes',
	'daggers in her eyes',
	'daggers in his eyes',

	// Weather/atmosphere clichés
	'the calm before the storm',
	'the eye of the storm',
	'when it rains it pours',
	'the fog lifted',
	'a heavy silence hung in the air',
	'tension thick enough to cut with a knife',
	'you could cut the tension with a knife',

	// Romance clichés
	'love at first sight',
	'swept off her feet',
	'swept off his feet',
	'head over heels',
	'meant to be',
	'destined to be together',
	'two halves of a whole',
	'their eyes met across the room',
	'felt the electricity between them',
	'sparks flew'
] as const;

/**
 * Telling indicators - words that often signal "telling" instead of "showing"
 * These suggest the author is stating emotions/reactions directly rather than
 * demonstrating them through action, dialogue, or sensory details
 */
export const TELLING_INDICATORS = [
	// Direct emotion labels
	'felt angry',
	'felt sad',
	'felt happy',
	'felt scared',
	'felt afraid',
	'felt nervous',
	'felt anxious',
	'felt excited',
	'felt relieved',
	'felt disappointed',
	'felt frustrated',
	'felt confused',
	'felt embarrassed',
	'felt ashamed',
	'felt guilty',
	'felt jealous',
	'felt proud',
	'felt lonely',
	'felt hopeful',
	'felt hopeless',

	'was angry',
	'was sad',
	'was happy',
	'was scared',
	'was afraid',
	'was nervous',
	'was anxious',
	'was excited',
	'was relieved',
	'was disappointed',
	'was frustrated',
	'was confused',
	'was embarrassed',
	'was ashamed',
	'was guilty',
	'was jealous',
	'was proud',
	'was lonely',
	'was hopeful',
	'was hopeless',

	// Sensory filters
	'could see',
	'could hear',
	'could feel',
	'could smell',
	'could taste',
	'could sense',

	// Character state descriptions
	'was beautiful',
	'was ugly',
	'was tired',
	'was exhausted',
	'was hungry',
	'was thirsty',
	'was cold',
	'was hot',
	'was uncomfortable'
] as const;

/**
 * Weak verbs that could often be replaced with stronger alternatives
 */
export const WEAK_VERBS = [
	'walked',
	'went',
	'got',
	'came',
	'made',
	'said',
	'looked',
	'moved',
	'put',
	'took',
	'had',
	'was',
	'were',
	'is',
	'are',
	'been',
	'being'
] as const;

/**
 * Words ending in -ly that are NOT adverbs (exceptions list)
 * These should not be flagged as adverbs
 */
export const LY_EXCEPTIONS = [
	'only',
	'early',
	'daily',
	'weekly',
	'monthly',
	'yearly',
	'holy',
	'lonely',
	'lovely',
	'ugly',
	'likely',
	'unlikely',
	'friendly',
	'family',
	'elderly',
	'orderly',
	'silly',
	'belly',
	'bully',
	'jelly',
	'jolly',
	'folly',
	'rally',
	'tally',
	'valley',
	'alley',
	'trolley',
	'volley',
	'pulley',
	'gully',
	'fully',
	'hilly',
	'chilly',
	'frilly',
	'smelly',
	'wooly',
	'curly',
	'burly',
	'surly',
	'pearly',
	'gnarly',
	'snarky',
	'italy',
	'assembly',
	'butterfly',
	'dragonfly',
	'firefly',
	'fly',
	'july',
	'reply',
	'supply',
	'apply',
	'multiply',
	'comply',
	'imply',
	'rely'
] as const;

/**
 * Common adverbs that don't end in -ly
 */
export const NON_LY_ADVERBS = [
	'very',
	'really',
	'quite',
	'rather',
	'almost',
	'already',
	'also',
	'always',
	'never',
	'ever',
	'often',
	'seldom',
	'sometimes',
	'soon',
	'still',
	'yet',
	'just',
	'even',
	'too',
	'well',
	'fast',
	'hard',
	'late',
	'near',
	'far',
	'long',
	'low',
	'high',
	'straight',
	'right',
	'wrong',
	'much',
	'little',
	'enough',
	'anywhere',
	'everywhere',
	'nowhere',
	'somewhere',
	'somehow',
	'anyway',
	'perhaps',
	'maybe'
] as const;

/**
 * Words that often indicate passive voice when followed by past participle
 */
export const PASSIVE_INDICATORS = [
	'was',
	'were',
	'is',
	'are',
	'been',
	'being',
	'be',
	'am',
	'get',
	'gets',
	'got',
	'getting'
] as const;

/**
 * Common irregular past participles
 */
export const IRREGULAR_PAST_PARTICIPLES = [
	'been',
	'done',
	'gone',
	'seen',
	'taken',
	'given',
	'known',
	'made',
	'found',
	'told',
	'left',
	'felt',
	'brought',
	'thought',
	'bought',
	'caught',
	'taught',
	'sought',
	'written',
	'driven',
	'eaten',
	'fallen',
	'forgotten',
	'chosen',
	'spoken',
	'stolen',
	'broken',
	'frozen',
	'hidden',
	'bitten',
	'beaten',
	'shaken',
	'woken',
	'worn',
	'torn',
	'sworn',
	'born',
	'borne',
	'drawn',
	'grown',
	'shown',
	'thrown',
	'blown',
	'flown',
	'slain',
	'lain',
	'paid',
	'said',
	'sent',
	'spent',
	'built',
	'burnt',
	'dealt',
	'dreamt',
	'dwelt',
	'kept',
	'knelt',
	'leant',
	'leapt',
	'learnt',
	'meant',
	'slept',
	'smelt',
	'spelt',
	'spilt',
	'swept',
	'wept',
	'lost',
	'shot',
	'hurt',
	'cut',
	'put',
	'shut',
	'hit',
	'let',
	'set',
	'rid',
	'spread',
	'read',
	'held',
	'hung',
	'dug',
	'stuck',
	'struck',
	'stung',
	'swung',
	'clung',
	'flung',
	'slung',
	'sprung',
	'sung',
	'rung',
	'begun',
	'drunk',
	'shrunk',
	'sunk',
	'swum',
	'run',
	'won'
] as const;

// Type exports for consumers
export type FilterWord = (typeof FILTER_WORDS)[number];
export type VagueWord = (typeof VAGUE_WORDS)[number];
export type Cliche = (typeof CLICHES)[number];
export type TellingIndicator = (typeof TELLING_INDICATORS)[number];
export type WeakVerb = (typeof WEAK_VERBS)[number];
