name: "diagnostics"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    diagnostics:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run lint
              run: bun run lint

            - name: Run check
              run: bun run check